### PR TITLE
OSSM-2203: aligns dependencies with istio/release-1.16

### PR DESCRIPTION
**Pull request by bartoszmajsak**
### Changes in this PR

- go module version to be 1.19
  - as this is the target version of upstream, also without it, it won't build easily - some deps explicitly require this version
- introduces default target
  - following the principle of least astonishment (POLA) running `make` should give reproducible builds (especially when starting from fresh clone)
- aligns dependencies with [`istio/istio@release-1.16`](https://github.com/istio/istio/blob/4788bbbc7bf2a3be69d85c9d75b56c4d3e68f478/go.mod)  branch
- the project does not rely on vendoring anymore

I used https://gist.github.com/bartoszmajsak/9359068bc8cead002a2fcf1ff947ad09 to automate majority of work.

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Ignore the build failures for now - that's the next thing on my list. And obviously, I targeted the wrong branch initially

**Comment by bartoszmajsak** [comment]
PR opened https://github.com/openshift/release/pull/33496

**Comment by bartoszmajsak** [comment]
Side note: I have handy template for `Makefile`s I can apply on this one... It needs some love :)

**Review by dgn — APPROVED** [review]

**Review by jwendell — COMMENTED** [review]
can we get rid of all stuff related to vendor?

We really don't need to vendor deps in this repo. It isn't even built in brew.

**Comment by bartoszmajsak** [comment]
> can we get rid of all stuff related to vendor?
> 
> We really don't need to vendor deps in this repo. It isn't even built in brew.

@jwendell done in 8f77795. I added few bits to `.gitignore`

**Review by jwendell — APPROVED** [review]

**Pull request merged**
