### PR TITLE
OSSM-5615: Sync with Istio 1.18.7

### PR DESCRIPTION
**Pull request by jewertow**

### CODE REVIEW

**Comment by luksa** [comment]
Are these the only changes between .0 and .7?

**Comment by jewertow** [comment]
I think so, because I was able to successfully build istio with this patch:
```
replace github.com/maistra/xns-informer => github.com/jewertow/xns-informer v0.0.0-20240111124030-7e694009c754
```

**Review by dgn — APPROVED** [review]

**Pull request merged**
